config/routes.rb
Rails.application.routes.draw do
resources :users do
  resources :comments
  # resources :comments, only: [:create, :destroy]
end
root "users#index"


  # get "/user", to: "user#index"
  # get "/user/:id", to: "user#show"

  # get "/user/new", to: "user#new"
  # post "/user/new", to: "user#new"
  # get "/user/edit/:id", to: "user#edit"
  # # post "/user" to:"user#create"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  validates :commenter, presence: true
  validates :aunty, presence: true
end

app/models/user.rb
class User < ApplicationRecord
    has_many :comments, dependent: :destroy
    validates :name, presence: true
    validates :game, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    # before_action :set_user
    
    # def index
    #     @user = User.all
    # end

    def show
        @user = User.find(params[:id])
        @comment = Comment.new
    end
     
    def new
        @user = User.new
    end

    def create
        @user = User.find(params[:user_id])
        @comment = @user.comments.new(comment_params)
        if @comment.save
          redirect_to @user, notice: 'Comment was successfully created.'
        else
          redirect_to @user, alert: 'Comment could not be created.'
        end
      end

    def destroy
        @user = User.find(params[:user_id])
        @comment = @user.comments.find(params[:id])
        @comment.destroy
        redirect_to user_path(@user), notice: 'Comment was successfully deleted.'
      end
  
    private
    # def set_user
        # @user = User.find(params[:user_id])
    #   end

      def comment_params
        params.require(:comment).permit(:commenter, :aunty)
      end
  end
  

app/controllers/users_controller.rb
class UsersController < ApplicationController

    def index
        @user = User.all
    end

    
    def show
        @user = User.find(params[:id])
        @comment = Comment.new
    end

   
     
    def new
        @user = User.new
    end

    def edit
        @user = User.find(params[:id])
    end

def create
    @user = User.new(user_params
        # name: params[:name],
        # game: params[:game]
    )
    if  @user.save
         redirect_to root_path, notice: 'User was successfully created.'
      else
        render :new
      end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
        redirect_to @user
    else
        render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy.
    redirect_to root_path
  end



  private
  def user_params
    params.require(:user).permit(:name, :game)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_comment.html.erb
<h2>Comments</h2>
<% @comment.comments.each do |japan| %>
  <p>
    <strong>Commenter:</strong>
    <%= japan.commenter %>
  </p>

  <p>
    <strong>Comment:</strong>
    <%= japan.aunty %>
  </p>
<% end %>

<h2>Add a comment:</h2>
<%= #form_with model: [ @user, @user.comments.build ] do |form| %>
  <p>
    <%=# form.label :commenter %><br>
    <%= #form.text_field :commenter %>
  </p>
  <p>
    <%= #form.label :aunty %><br>
    <%=# form.text_area :aunty %>
  </p>
  <p>
    <%=# form.submit %>
  </p>
<% end %>

app/views/comments/edit.html.erb
<h1>Editor</h1>

<%= render "comment", user: @comment %>


 <%= link_to 'Back to Dashboard', root_path %>

app/views/comments/index.html.erb
<h2>Comments</h2>
<% @user.comments.each do |comment| %>
  <p>
    <strong>Commenter:</strong>
    <%= comment.commenter %>
  </p>

  <p>
    <strong>Comment:</strong>
    <%= comment.aunty %>
  </p>
  
<%= link_to 'edit', edit_user_comment_path(japan.id) %>

<% end %>

app/views/comments/show.html.erb
<h1><%= @user.name %></h1>

<p style="color:black"><%= @user.game %></p>


  <% @user.comments.each do |comment| %>
    <ul>
      <%= comment.commenter %>
      <%= comment.aunty %>
<%= link_to 'daestro', [comment.user, comment], data: {  
        turbo_method: :delete,
        turbo_confirm: "Are you sure?" } %>
    </ul>
  <% end %>
</ul>

<p></p>
<%= link_to 'Back to Dashboard', root_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Last" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/_form.html.erb
<%= form_with model: @user do |form| %>
    <div>
      <%= form.label :name %><br>
      <%= form.text_field :name %>
     </div>

     <div>
     <%= form.label :game %><br>
     <%= form.text_field :game %>
     </div>
     
     <div>
        <%= form.submit %>
     </div>

<% end %>

app/views/users/edit.html.erb
<h1>Edit DD</h1>

<%= render "form", user: @user %>


 <%= link_to 'Back to Dashboard', root_path %>

app/views/users/index.html.erb
<h1>Dashboard</h1>


<%= link_to 'New Creation', new_user_path %>

    <style type="text/css">
           table, th, td{
             border: 1px solid ;
           }
    </style>

<table style="width: 100%">
    <thead>
    <tr>
     <th>name</th>
     <th>game</th>
     <th>update</th> 
     <th>show</th> 
     <th>gossips</th> 
     <th>illuminati</th> 
    </tr>
    </thead>

    <tbody>
  <% @user.each do |human| %>
    <tr>
       <td><%=link_to human.name, human %></td>
       <td><%= human.game %></td>
       <td><%= link_to 'edit', edit_user_path(human.id) %></td>
       <td><%= link_to 'show', user_path(human.id) %></td>
       <td><%= link_to 'gossips', user_comment_path(human.id,human.id) %></td>
       <td><%= link_to 'daestro', user_path(human.id), data: {  
        turbo_method: :delete,
        turbo_confirm: "Are you sure?" } %></td>
   </tr>
     <% end %>
    </tbody>
 </table>   

app/views/users/new.html.erb
<h1>New Creation</h1>

<%= form_with model: @user,local:true do |form| %>
    <div>
      <%= form.label :name %><br>
      <%= form.text_field :name %>
     </div>

     <div>
     <%= form.label :game %><br>
     <%= form.text_area :game %>
     </div>
     
     <div>
        <%= form.submit %>
     </div>

<% end %>

 <%= link_to 'Back to Dashboard', root_path %>

app/views/users/show.html.erb
<h1><%= @user.name %></h1>

<p style="color:black"><%= @user.game %></p>


<ul>
  <li><%= link_to "Edit", edit_user_path(@user) %></li>
</ul>

<%= link_to 'Back to Dashboard', root_path %>


<h2>Comments</h2>
<%= form_with(model: [@user, @comment], local: true) do |form| %>
  <div>
    <%= form.label :commenter %>
    <%= form.text_area :commenter %>
  </div>
  <div>
    <%= form.label :aunty %>
    <%= form.text_area :aunty %>
  </div>
  <div>
    <%= form.submit 'Add Comment' %>
  </div>
<% end %>

<ul>
  <% @user.comments.each do |comment| %>
    <li>
      <%= comment.commenter %>
      <%= comment.aunty %>
      <%= link_to "Daestro", [comment.user, comment], data: {
        turbo_method: :delete,
        turbo_confirm: "Are you sure?"
      } %>    </li>
  <% end %>
</ul>